spring:
  main-application-type: reactive
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /auth/${segment}

        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/member/(?<segment>.*), /member/${segment}

        - id: ui-service
          uri: lb://ui-service
          predicates:
            - Path=/api/public/ui/**, /api/ui/**
          filters:
            - RewritePath=/api(?:/public)?/ui/(?<segment>.*), /ui/${segment}

        - id: ad-service
          uri: lb://ad-service
          predicates:
            - Path=/api/public/ad/**, /api/ad/**
          filters:
            - RewritePath=/api(?:/public)?/ad/(?<segment>.*), /ad/${segment}

        - id: ad-admin-service
          uri: lb://ad-admin-service
          predicates:
            - Path=/api/public/ads/**, /api/ads/**
          filters:
            - RewritePath=/api(?:/public)?/ads/(?<segment>.*), /ads/${segment}

        - id: content-service
          uri: lb://content-service
          predicates:
            - Path=/api/public/contents/**, /api/contents/**
          filters:
            - RewritePath=/api(?:/public)?/contents/(?<segment>.*), /contents/${segment}

        - id: indexing-service
          uri: lb://indexing-service
          predicates:
            - Path=/index/**
          filters:
            - RewritePath=/index/(?<segment>.*), /index/${segment}

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/public/review/**, /api/review/**
          filters:
            - RewritePath=/api(?:/public)?/review/(?<segment>.*), /review/${segment}

        - id: subscribe-service
          uri: lb://subscribe-service
          predicates:
            - Path=/api/public/subscribe/**, /api/subscribe/**
          filters:
            - RewritePath=/api(?:/public)?/subscribe/(?<segment>.*), /subscribe/${segment}

        - id: userAction-test-service
          uri: lb://userAction-test-service
          predicates:
            - Path=/api/public/events/**, /api/events/**
          filters:
            - RewritePath=/api(?:/public)?/events/(?<segment>.*), /events/${segment}
      default-filters:
        PreserveHostHeader

server:
  port: 8080


service:
  jwt:
    secret-key: "pA1Qb6q8vXqWn4FQ8zQ2h6V7Q6k3y8fB3wZ2s9T1n4m5c6p7v8w9x0y1z2A3B4C5D6E7F8G9H0I1J2K3L4M5N6O7P8Q9R0S1T2U3V4W5X6Y7Z8"



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://gpadmin:1234@localhost:8761/eureka

security:
  permit-paths: >
    /api/public/**,
    /api/auth/**,
    /static/**

# 정적 리소스 서빙 설정
  web:
    resources:
      static-locations: classpath:/static/  # 리액트 빌드 결과가 들어갈 위치