spring:
  main-application-type: reactive
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service #인증 서비스
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /api/auth/$\{segment}
        - id: member-service #멤버 서비스
          uri: lb://member-service
          predicates:
            - Path=/member/**
          filters:
            - RewritePath=/member/(?<segment>.*), /api/member/$\{segment}
        - id: ui-service # 유저 인터렉션(좋아요) 서비스
          uri: lb://ui-service
          predicates:
            - Path=/ui/**
          filters:
            - RewritePath=/ui/(?<segment>.*), /api/ui/$\{segment}
        - - id: ad-service # 광고 서비스
            uri: lb://ad-service
            predicates:
              - Path=/ad/**
            filters:
              - RewritePath=/ad/(?<segment>.*), /api/ad/$\{segment}
      default-filters:
        PreserveHostHeader

server:
  port: 8080


service:
  jwt:
    secret-key: "pA1Qb6q8vXqWn4FQ8zQ2h6V7Q6k3y8fB3wZ2s9T1n4m5c6p7v8w9x0y1z2A3B4C5D6E7F8G9H0I1J2K3L4M5N6O7P8Q9R0S1T2U3V4W5X6Y7Z8"



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://gpadmin:1234@localhost:8761/eureka

security:
  permit-paths: /api/auth/signin,/api/auth/signup,/api/public/**