apiVersion: v1
kind: ConfigMap
metadata:
  name: apigateway-config
  namespace: apigateway
data:
  EUREKA_URL: http://eureka-service.default.svc.cluster.local:8761/eureka
  SPRING_PROFILES_ACTIVE: prod
  S3_FRONTEND_ORIGIN: http://goorm-front.s3-website.ap-northeast-2.amazonaws.com
