apiVersion: v1
kind: ConfigMap
metadata:
  name: apigateway-service-config
  namespace: apigateway
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_SERVER_PORT: "8080"
  EUREKA_URL: http://eureka-service.eureka.svc.cluster.local:8761/eureka
  S3_FRONTEND_ORIGIN: http://goorm-front.s3-website.ap-northeast-2.amazonaws.com
