apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-service
  namespace: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway-service
  template:
    metadata:
      labels:
        app: apigateway-service
    spec:
      containers:
        - name: apigateway
          image: roin09/apigateway-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: apigateway-config
            - secretRef:
                name: apigateway-secret
