apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: apigateway-service-secret
  namespace: apigateway
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: apigateway-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: apigateway-service-secret
