nameOverride: apigateway
fullnameOverride: apigateway-service
image:
  repository: roin09/apigateway-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  useConfigMap: true
  useSecret: true

replicaCount: 1

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  host: "api.aws-test-site.shop"

externalSecret:
  enabled: true
  refreshInterval: 1h
  secretStore:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  dataFromKey: apigateway-service-secret

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
            - key: node-type
              operator: In
              values:
                - high

resources:
  requests:
    cpu: 300m
    memory: 384Mi
  limits:
    cpu: 500m
    memory: 512Mi
