image:
  repository: roin09/apigateway-service
  tag: latest

service:
  port: 80
  targetPort: 8080

env:
  useConfigMap: true
  useSecret: true
ingress:
  enabled: true
  host: api.aws-test-site.shop